// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:a972f9bf-4db5-44b6-a335-681041d47155",
    "aws_cognito_region": "eu-west-2",
    "oauth": {},
    "aws_mobile_analytics_app_id": "008b8fda4c4c4b70afb549633107b6f6",
    "aws_mobile_analytics_app_region": "eu-west-1"
};


export default awsmobile;
